# Example docker-compose file
version: '3'
services:
  dokuwiki:
    image: 'ununseptium/dokuwiki-docker'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'data:/var/www/html/data'
volumes:
  data:
    driver: local
