# Example docker-compose file
version: '2'
services:
  dokuwiki:
    image: 'ununseptium/dokuwiki-docker'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - 'data':/var/www/html'
volumes:
  data:
    driver: local
